### PR TITLE
skeleton of the code added

### PR DESCRIPTION
**Pull request by asp002**

### CODE REVIEW

**Review by AnirudhG07 — CHANGES_REQUESTED** [review]
Hey, can you change the code location? I have changed the repo's file structure a bit so it wont match now. 
You have to add it to /gen/pdb2pqr.py now.
Hope it's clear.

**Comment by AnirudhG07** [comment]
Also there is an issue you need to look.
When you install pdb2pqr from sudo apt, you get v2.1.1, while if you install using pip, you get v3.6.2
Version 3.6.2 has a bit different options compared to v2.1.1
So your main reference should be v3.6.2. The web server as far as i have seen goes for v3.6.2 so you should be safe.

One more thing, before you mark for final review, make sure whatever option you chose, the command created RUNS.
How can you do that? create all possible commands automatically using some loop. and then run each of them.

**Comment by asp002** [comment]
Ok, so I did install pdb2pqr vis sudo apt on WSL, but I'm not sure how that's going to change what I'm coding since I am only following the commands given on the Web Server

Can you elaborate on the runs part? Do you want me to make all the permutations of the pdb2pqr run commands and run them on terminal?

**Comment by AnirudhG07** [comment]
Why did you close it? Anyways, I hope you can put the pdb2pqr by the end of the day

**Pull request closed without merging**
